# These can also be created from the command line using environment variables
#
# kubectl create secret generic redis-creds --from-literal=uri=$DATABASE_URI
#
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: cG9zdGdyZXM=
  uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
